"""Composed loader: LinkedIn preamble skip, company grouping, the
census+summary+referrers card join, and derived-CSV round-trip."""

from referral_prioritizer import judge_data

_CONNECTIONS = """Notes:
"Some preamble text the export always carries"

First Name,Last Name,URL,Email Address,Company,Position,Connected On
Jane,Doe,https://linkedin.com/in/jane,,Acme,Engineer,01 Jan 2020
John,Roe,https://linkedin.com/in/john,,Acme,Manager,02 Feb 2021
Solo,Person,https://linkedin.com/in/solo,,Beta,CTO,03 Mar 2022
"""

_COMPANIES = """company,n_connections,board_kind,board_note,n_postings_theirstack
Acme,2,greenhouse,note here,
Beta,1,none,,7
"""

_SUMMARY = """company,n_connections,board_kind,board_slug,scan_source,n_located,n_scanned,n_precut,n_prefiltered,swe_strong,swe_stretch,swe_long_shot,swe_blocked,swe_top1,swe_top2,swe_top3,post_sales_se_strong,post_sales_se_stretch,post_sales_se_long_shot,post_sales_se_blocked,post_sales_se_top1,post_sales_se_top2,post_sales_se_top3,pre_sales_se_strong,pre_sales_se_stretch,pre_sales_se_long_shot,pre_sales_se_blocked,pre_sales_se_top1,pre_sales_se_top2,pre_sales_se_top3
Acme,2,greenhouse,acme,native,10,8,0,2,1,2,3,2,Title A | https://x/1,,,0,0,0,0,,,,0,0,0,0,,,
"""


def test_load_connections_groups_and_skips_preamble(tmp_path):
    p = tmp_path / "Connections.csv"
    p.write_text(_CONNECTIONS)
    groups = judge_data.load_connections(p)
    assert set(groups) == {"Acme", "Beta"}
    assert [c["name"] for c in groups["Acme"]] == ["Jane Doe", "John Roe"]
    assert groups["Beta"][0]["id"] == "https://linkedin.com/in/solo"


def test_company_cards_join(tmp_path):
    companies = tmp_path / "Companies.csv"
    companies.write_text(_COMPANIES)
    summary = tmp_path / "summary.csv"
    summary.write_text(_SUMMARY)
    referrers = tmp_path / "referrers.csv"
    judge_data.write_referrers(
        referrers,
        [
            {
                "company": "Acme",
                "rank": 2,
                "name": "John Roe",
                "position": "Manager",
                "url": "u2",
            },
            {
                "company": "Acme",
                "rank": 1,
                "name": "Jane Doe",
                "position": "Engineer",
                "url": "u1",
            },
        ],
    )
    cards = {
        c["company"]: c for c in judge_data.company_cards(companies, summary, referrers)
    }
    acme = cards["Acme"]
    assert acme["scan_source"] == "native"
    assert acme["tier_counts"]["swe"]["strong"] == "1"
    assert acme["top_postings"] == ["Title A | https://x/1"]
    assert [r["name"] for r in acme["referrers"]] == [
        "Jane Doe",
        "John Roe",
    ]  # rank order
    beta = cards["Beta"]
    assert beta["scan_source"] == "" and beta["referrers"] == []


def test_derived_csv_round_trip(tmp_path):
    p = tmp_path / "tiers.csv"
    judge_data.write_tiers(p, {"Beta": "B", "Acme": "A"})
    assert p.read_text().startswith("# generated by")
    rows = judge_data.read_derived(p)
    assert rows == [
        {"company": "Acme", "tier": "A"},
        {"company": "Beta", "tier": "B"},
    ]
