"""Composed data layer for the judging TUI and its derived artifacts.

One loader joins the census, summary.csv, and stage-1 referrers into card
dicts consumed by every TUI mode; the same join powers the exported CSVs.
Derived CSVs open with a `# generated by ...` comment naming the command —
they encode human judgment (plus a snapshot of the machine context it was
made in) and are meant to be committed in the consuming project.
"""

import csv
from collections import defaultdict
from pathlib import Path

_ROLE_KEYS = ("swe", "post_sales_se", "pre_sales_se")
_TIERS = ("strong", "stretch", "long_shot", "blocked")


def load_connections(path: Path) -> dict[str, list[dict]]:
    """LinkedIn Connections.csv, grouped by Company. The export opens with a
    notes preamble of variable length; the header row is found by prefix."""
    lines = Path(path).read_text(encoding="utf-8-sig").splitlines()
    start = next(
        (i for i, line in enumerate(lines) if line.startswith("First Name,")), None
    )
    if start is None:
        raise SystemExit(f"{path}: no LinkedIn header row found")
    by_company: dict[str, list[dict]] = defaultdict(list)
    for r in csv.DictReader(lines[start:]):
        company = (r.get("Company") or "").strip()
        name = f"{(r.get('First Name') or '').strip()} {(r.get('Last Name') or '').strip()}".strip()
        if not company or not name:
            continue
        by_company[company].append(
            {
                "id": (r.get("URL") or "").strip() or f"{name} @ {company}",
                "name": name,
                "position": (r.get("Position") or "").strip(),
                "connected_on": (r.get("Connected On") or "").strip(),
                "url": (r.get("URL") or "").strip(),
                "company": company,
            }
        )
    return dict(by_company)


def read_derived(path: Path) -> list[dict]:
    """Derived-CSV reader: skips the leading # comment line(s)."""
    lines = [
        line for line in Path(path).read_text().splitlines() if not line.startswith("#")
    ]
    return list(csv.DictReader(lines))


def _write_derived(path: Path, command: str, fieldnames: list[str], rows) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        f.write(f"# generated by {command}\n")
        w = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        w.writeheader()
        w.writerows(rows)


def company_cards(
    companies_csv: Path,
    summary_csv: Path | None,
    referrers_csv: Path | None,
) -> list[dict]:
    """One card dict per census row: census + summary + top-3 referrers."""
    summary: dict[str, dict] = {}
    if summary_csv and Path(summary_csv).exists():
        summary = {r["company"]: r for r in csv.DictReader(open(summary_csv))}
    referrers: dict[str, list[dict]] = defaultdict(list)
    if referrers_csv and Path(referrers_csv).exists():
        for r in read_derived(referrers_csv):
            referrers[r["company"]].append(r)

    cards = []
    for r in csv.DictReader(open(companies_csv)):
        if not r.get("company"):
            continue
        s = summary.get(r["company"], {})
        cards.append(
            {
                "company": r["company"],
                "n_connections": r.get("n_connections", ""),
                "positions": r.get("positions", ""),
                "board_kind": r.get("board_kind", ""),
                "board_note": r.get("board_note", ""),
                "scan_source": s.get("scan_source", ""),
                "n_scanned": s.get("n_scanned", ""),
                "tier_counts": {
                    rk: {t: s.get(f"{rk}_{t}", "") for t in _TIERS} for rk in _ROLE_KEYS
                }
                if s
                else {},
                "top_postings": [
                    s[f"swe_top{i}"] for i in (1, 2, 3) if s.get(f"swe_top{i}")
                ],
                "referrers": sorted(
                    referrers.get(r["company"], []), key=lambda x: int(x["rank"])
                )[:3],
            }
        )
    return cards


def write_referrers(path: Path, rows: list[dict]) -> None:
    _write_derived(
        path,
        "referral_prioritizer.judge referrers",
        ["company", "rank", "name", "position", "url"],
        rows,
    )


def write_tiers(path: Path, tiers: dict[str, str]) -> None:
    _write_derived(
        path,
        "referral_prioritizer.judge tier",
        ["company", "tier"],
        [{"company": c, "tier": t} for c, t in sorted(tiers.items())],
    )


def write_ranking(path: Path, rows: list[dict]) -> None:
    _write_derived(
        path,
        "referral_prioritizer.judge rank",
        [
            "tier",
            "rank",
            "utility",
            "wins",
            "losses",
            "ties",
            "company",
            "n_connections",
            "scan_source",
            "referrers",
            "top_posting",
        ],
        rows,
    )
